### ISSUE TITLE
Feature Request: Method to extract tokens as a list of strings

### ISSUE THREAD

**Issue by cilerler** [tryAGI/Tiktoken#2]
As a developer, I'm in need of a method to retrieve tokens from the parsing/processing stage as a list of strings. This would enhance visibility over the tokenization process, facilitate token manipulation, and could serve as a useful tool for educational purposes.

**Comment by HavenDV** [comment]
Added in https://github.com/tryAGI/Tiktoken/commit/9bc959afc10aa67921dd987b6acfa4d588b2bcdc

**Comment by cilerler** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/e6518353-71e9-41b7-9208-fde8f676bf08-ccdabca3-9682-4342-aa5e-1222b8adc35f-v1.png?transparent=1&palette=1&width=246)

**Comment by lofcz** [comment]
@HavenDV currently the implementation is not UTF-safe, the same as in the OAI's demo, which is ok. However for some use cases it is useful to get the tokens in a printable format. I'm not proposing this as a PR as it works only on .NET 8+ due to `Utf8.IsValid` (could be shimmed if you would find this as something to include in the library). Consider an example string ` řeknu` to tokenize:

Current implementation:
![image](https://github.com/tryAGI/Tiktoken/assets/10260230/74bccbb6-5a66-49ca-af5b-d0efd215ca83)

OpenAI in their Python implementation warns about their counterpart method not being UTF-safe: https://github.com/openai/tiktoken/blob/1b9faf2779855124f05174adf1383e53689ed94b/tiktoken/core.py#L246

The printable version here would be:
![image](https://github.com/tryAGI/Tiktoken/assets/10260230/e97988fb-f3a1-4f84-860d-595ca80c15fd)

Where the number after each token denotes the number of tokens physically used to encode the token (one or more).
This isn't a particullary efficient implementation however I believe it works: https://gist.github.com/lofcz/7a25b24f984b5aea3fbb3bb9a6e17004

**Comment by HavenDV** [comment]
@lofcz Thank you very much for your detailed comment. Indeed, this can also be seen in the tests; we do not cover some scenarios.
I'll investigate/benchmark the code you suggest, but I'd be happy to accept PR regarding this if possible.

**Comment by lofcz** [comment]
@HavenDV I've opened #19. The implementation is faster starting with .NET 8, as it shims the check of  `byte[]` UTF-8 validity with a slower `try-catch` on older runtimes. If you have anything faster for that on hand please, let me know.
